### PR TITLE
WIP: Converts vocabularies to OWL ontologies

### LINKED ISSUE #361: Convert vocabularies to OWL ontologies
In order to use automated ontology documentation tools, such as [pyLODE](https://github.com/RDFLib/pyLODE), we need to convert the vocabularies into OWL ontologies.

Converting them to OWL is straightforward since  we simply need to: 1) state that the vocabulary is an `owl:Ontology`, and 2) change all instances `rdf:class` to instances of `owl:Class`.

For example
```turtle
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:    <http://www.w3.org/2000/10/XMLSchema#> .
@prefix dc:     <http://purl.org/dc/elements/1.1/> .
@prefix lr:     <http://w3id.org/hefquin/lpg2rdf#> .

<http://w3id.org/hefquin/lpg2rdf>
    dc:creator       "Olaf Hartig" ;
    dc:date          "2023-11-29" ;
    dc:format        "RDF" ;
    dc:identifier    <http://w3id.org/hefquin/lpg2rdf> ;
    dc:title         "Vocabulary for describing LPG-to-RDF configurations"@en ;
    rdfs:label       "Vocabulary for describing LPG-to-RDF configurations"@en ;
    dc:description   "This vocabulary can be used to describe LPG-to-RDF configurations which are the basis of the user-configurable LPG-to-RDF mapping that is defined in the paper titled 'Foundations to Query Labeled Property Graphs using SPARQL*' by Olaf Hartig (2019) and that is implemented in HeFQUIN."@en ;
    rdfs:comment     "This vocabulary can be used to describe LPG-to-RDF configurations which are the basis of the user-configurable LPG-to-RDF mapping that is defined in the paper titled 'Foundations to Query Labeled Property Graphs using SPARQL*' by Olaf Hartig (2019) and that is implemented in HeFQUIN."@en .

## ==== CLASS DECLARATIONS ====

lr:LPGtoRDFConfiguration rdf:type rdfs:Class ;
    rdfs:label      "LPG-to-RDF Configuration"@en ;
    rdfs:comment    "Class of LPG-to-RDF configurations. Instances of this class must have exactly one lr:nodeMapping property, one lr:nodeLabelMapping property, one lr:edgeLabelMapping property, one lr:propertyNameMapping property, and one lr:labelPredicate property."@en .
```

would become:

```turtle
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:    <http://www.w3.org/2002/07/owl#> .
@prefix xsd:    <http://www.w3.org/2000/10/XMLSchema#> .
@prefix dc:     <http://purl.org/dc/elements/1.1/> .
@prefix lr:     <http://w3id.org/hefquin/lpg2rdf#> .

<http://w3id.org/hefquin/lpg2rdf>
    a owl:Ontology ;
    dc:creator       "Olaf Hartig" ;
    dc:date          "2023-11-29" ;
    dc:format        "RDF" ;
    dc:identifier    <http://w3id.org/hefquin/lpg2rdf> ;
    dc:title         "Vocabulary for describing LPG-to-RDF configurations"@en ;
    rdfs:label       "Vocabulary for describing LPG-to-RDF configurations"@en ;
    dc:description   "This vocabulary can be used to describe LPG-to-RDF configurations which are the basis of the user-configurable LPG-to-RDF mapping that is defined in the paper titled 'Foundations to Query Labeled Property Graphs using SPARQL*' by Olaf Hartig (2019) and that is implemented in HeFQUIN."@en ;
    rdfs:comment     "This vocabulary can be used to describe LPG-to-RDF configurations which are the basis of the user-configurable LPG-to-RDF mapping that is defined in the paper titled 'Foundations to Query Labeled Property Graphs using SPARQL*' by Olaf Hartig (2019) and that is implemented in HeFQUIN."@en .

## ==== CLASS DECLARATIONS ====

lr:LPGtoRDFConfiguration
    a owl:Class ;
    rdfs:label      "LPG-to-RDF Configuration"@en ;
    rdfs:comment    "Class of LPG-to-RDF configurations. Instances of this class must have exactly one lr:nodeMapping property, one lr:nodeLabelMapping property, one lr:edgeLabelMapping property, one lr:propertyNameMapping property, and one lr:labelPredicate property."@en .
```

### PR DESCRIPTION
**Pull request by hartig**
Closes #361

### CODE REVIEW

**Comment by hartig** [comment]
@keski  Related to my last point in https://github.com/LiUSemWeb/HeFQUIN/issues/348#issuecomment-2371030129, it is not clear to me why we need to copies of these files in the `./hefquin-vocabs/` directory. And since you made an actual copy, I don't see what exactly has been changed in comparison to the original versions. If your intention is to replace the old versions of these two files by the new versions, with the new names, then please do it using `git mv`.

**Comment by keski** [comment]
The only difference between the files is the addition of the triples that state that the vocabularies are OWL ontologies:
```turtle
<http://w3id.org/hefquin/engineconf> rdf:type owl:Ontology ;
...
```
```turtle
<http://w3id.org/hefquin/lpg2rdf> rdf:type owl:Ontology ;
...
```

**Comment by hartig** [comment]
... and the renaming of the namespace, and the change from rdfs:Class to owl:Class, right? (as I understood from your earlier comments somewhere else)

**Comment by keski** [comment]
> ... and the renaming of the namespace, and the change from rdfs:Class to owl:Class, right? (as I understood from your earlier comments somewhere else)

Yes, that's right.

With the latest commits. I've now also propagated the updated namespace into the actual code base.

**Comment by keski** [comment]
Darn, forgot to use `git mv`...

**Comment by keski** [comment]
There, now the history of the vocabularies show that they have been renamed (`git mv`).

**Comment by hartig** [comment]
Perfect! Anything left in this PR?

**Comment by hartig** [comment]
Okay. I have run the `build.sh` script locally and everything works as expected.

I will merge the PR now.

**Pull request merged**
